version: '2.3'

services:
    app:
        container_name: densepose_container
        image: densepose_image
        runtime: nvidia
        volumes:
            - ${PWD}/DensePose/DensePoseData:/denseposedata
            - ${PWD}/DensePose/DensePoseData:/densepose/DensePoseData
            - ${PWD}/results:/densepose/results
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "5003:5003"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
